from validazione.holdout import Holdout
from validazione.random_subsampling import RandomSubsampling
from validazione.stratified_validation import StratifiedValidation
from validazione.validazione_main import KNNValidation_main